### ISSUE TITLE
Push data error

### ISSUE THREAD

**Issue by PabloLefort** [praekeltfoundation/docker-graphite#7]
Hi!
Simple cuestion, running this container i'm trying to send some data. I'm using [graphitesend](https://github.com/daniellawrence/graphitesend) and hiting on default port `8000` but nothing saves.

Also, the hit does not appear on the log when running docker on interactive mode.

Appreciate your's help, thanks in advance!

**Comment by jpaidoussi** [comment]
The 8000 port is for the graphite web interface so you may need to publish the carbon ports separately if you want to communicate directly with carbon.

**Comment by PabloLefort** [comment]
@jpaidoussi Perfect, i was thinking on that. 
The solution was:
`docker run -i -p 8002:8000 -p 8004:2003 -v /local/storage:/opt/graphite/storage praekeltfoundation/graphite`

Graphite web runs on `localhost:8000` and Carbon on `localhost:8004`

Thanks!

**Comment by JayH5** [comment]
Thanks @jpaidoussi :cake:

I've create #8 to make sure it's clearer what ports are available for use.

**Comment by PabloLefort** [comment]
Awesome @JayH5 !
